export const ICONS = {
  home: 'home-outline',
  homeFilled: 'home',
  history: 'clock-outline',
  permit: 'file-document-edit-outline',
  profile: 'account-outline',
  profileFilled: 'account',
  queue: 'format-list-bulleted',
  dashboard: 'view-dashboard-outline',
  dashboardFilled: 'view-dashboard',
  notification: 'bell-outline',
  notificationFilled: 'bell',
  back: 'arrow-left',
  add: 'plus',
  send: 'send',
  search: 'magnify',
  close: 'close',
  check: 'check',
  reject: 'close-circle-outline',
  qrCode: 'qrcode',
  logout: 'logout',
  settings: 'cog-outline',
  calendar: 'calendar-month-outline',
  clock: 'clock-outline',
  attachment: 'paperclip',
  chevronRight: 'chevron-right',
} as const;
